### ISSUE TITLE
Broken Link: External User Guide Fix 

### ISSUE THREAD

**Issue by sterling-platinum** [GoogleCloudPlatform/automlops#34]
The AutoMLOps - Introduction Training Example has a User Guide section, with the following text:

For a user-guide, please view these [slides](https://github.com/GoogleCloudPlatform/automlops/blob/bafd3558a6d1063724f38dab3acd9e8b7842785b/examples/AutoMLOps_Implementation_Guide_External.pdf).

However, the link is broken and results in an error:

**404 - page not found**
The bafd3558a6d1063724f38dab3acd9e8b7842785b branch of automlops does not contain the path examples/AutoMLOps_Implementation_Guide_External.pdf.

I have attached the missing external User Guide doc for upload/ replacement/

[AutoMLOps_Implementation_Guide_External.pdf](https://github.com/GoogleCloudPlatform/automlops/files/12196890/AutoMLOps_Implementation_Guide_External.pdf)

**Comment by srastatter** [comment]
Fixed
